### ISSUE TITLE
Node-Red Crash if i switch

### ISSUE THREAD

**Issue by heydemar** [nobodyMO/node-red-contrib-rcswitch2#3]
In my log i find this information: 

20 Sep 08:03:39 - [error] [link out:d42f3b0d.f3f188] RangeError: Maximum call stack size exceeded
20 Sep 08:03:39 - [error] [ui_switch:9edce623.807ec] RangeError: Maximum call stack size exceeded
20 Sep 08:03:39 - [error] [rcswitch:11110-A] RangeError: Maximum call stack size exceeded
20 Sep 08:03:39 - [error] [rcswitch:11110-A] RangeError: Maximum call stack size exceeded
20 Sep 08:03:39 - [error] [rcswitch:11110-A] RangeError: Maximum call stack size exceeded
20 Sep 08:03:39 - [error] [rcswitch:11110-A] RangeError: Maximum call stack size exceeded
20 Sep 08:03:39 - [error] [rcswitch:11110-A] RangeError: Maximum call stack size exceeded

//EDIT: The rcswitch is not the Problem - the last Update of the Node-Red-Dashboard 
https://github.com/node-red/node-red-dashboard/issues/280

**Comment by nobodyMO** [comment]
hi heydemar,
I can't understand the problem at the moment, because I don't use the dashboard and the problem hasn't occurred with others yet. 
I have understood that there is now an issue report for node-red. That's why I'll wait here for a while.
Please tell me if the problem could be solved there.
