### ISSUE TITLE
Receiving input node

### ISSUE THREAD

**Issue by insolite** [nobodyMO/node-red-contrib-rcswitch2#4]
Hi! Are there any plans for adding of code receiving input node? I've made a [request](https://github.com/marvinroger/node-rcswitch/issues/11) for integrating of receiving features of `rcswitch` to `node-rcswitch` bindings recently. If/when it will be released would you mind to add corresponding node? I'd be glad to help with PR, but I'm mostly operating raw codes, so I'm kinda beyond that devices/groups logic. I only have some working prototype based on [this simplest fork](https://github.com/Jakob-Gliwa/node-red-contrib-rcswitch/blob/master/rcswitch/rcswitch.js):

```js
module.exports = function (RED) {
    function RCSwitchNodeReceive(config) {
        RED.nodes.createNode(this, config);
        var node = this;
        node.pin = parseInt(config.pin);
        var rcswitch = require('rcswitch');
        rcswitch.enableReceive(node.pin);
        node.interval = setInterval(function () {
            if (rcswitch.available()) {
                var code = rcswitch.getReceivedValue();
                node.send({payload: code});
                rcswitch.resetAvailable();
            }
        }, 500);
    }

    RED.nodes.registerType("rcswitch-receive", RCSwitchNodeReceive);
};
```

**Comment by nobodyMO** [comment]
Hi insolite,
So far I had no plans to add an input node to the package.
I can integrate that. But I don't have any devices to test the function. 
But I'm bothered that the data is polled in an interval of 500ms. This should result in an unnecessary workload on the system. A call back function would be a better solution.

**Comment by slash-oleh** [comment]
Of course the callback is better rather than polling interval, but seems like [that's how rcswitch receiving intended to work](https://github.com/ninjablocks/433Utils/blob/b858d9bc6b555439f721a2092051ec531db25135/RPi_utils/RFSniffer.cpp#L40-L58). However in most cases there are no data and the only function called repeatedly is `available` which has only a single equality check [under the hood](https://github.com/sui77/rc-switch/blob/a9da9c36820b02fc5613dfe2437e1187bcf5b402/RCSwitch.cpp#L565-L567), which should not be so crucial. We can try build some kind of polling thread on the C level with callback, but I guess we'll not gain so much performance from dissolving of a few function calls. After all, fixed 500ms is just a part of example, so I think it should become at least a configurable node field.
For now I have that kind of node working:
```js
module.exports = function (RED) {
    function RCSwitchNodeReceive(config) {
        RED.nodes.createNode(this, config);
        var node = this;
        var pin = parseInt(config.pin);
        var interval = parseInt(config.interval);
        var rcswitch = require('rcswitch');
        rcswitch.enableReceive(pin);
        node.interval = setInterval(function () {
            if (rcswitch.available()) {
                var code = rcswitch.getReceivedValue();
                node.send({payload: code});
                rcswitch.resetAvailable();
            }
        }, interval);
        this.on('close', function() {
            clearInterval(node.interval);
            rcswitch.disableReceive();
        });
    }

    RED.nodes.registerType("rcswitch-receive", RCSwitchNodeReceive);
};
```

**Comment by slash-oleh** [comment]
FYI, since I didn't get any response for such [node-rcswitch feature request](https://github.com/marvinroger/node-rcswitch/issues/11) I've forked and implemented it on my own [here (node-rcswitch2)](https://github.com/insolite/node-rcswitch2) and did [another fork](https://github.com/insolite/node-red-contrib-rcswitch3) from original `node-red-contrib-rcswitch` which is now based on `node-rcswitch2`. I'm okay with using it from github directly so I didn't publish that to `npm` in case it will be integrated into original libraries someday.
So, thanks for response anyway and if suddenly that `node-rcswitch` modification will be interesting to you just reply and I'll publish it to `npm`.
