### ISSUE TITLE
Fails to install rcswitch2 on new pi 3B with latest software

### ISSUE THREAD

**Issue by VogelP** [nobodyMO/node-red-contrib-rcswitch2#6]
Hi,
as per instructions i first installed wiringPi, then opened the node-red palette manager to install rcswitch2. When installation failed, i then proceeded to install via terminal using:
sudo npm install node-red-contrib-rcswitch2 --unsafe-perm
Installation failed again.

Attached is the Log file from the palette manager installation attempt and the log from the npm install attempt.

I noticed that the following line appears repeatedly in the npm install log:
V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);

[Log_npmInstallFromTerminal.txt](https://github.com/nobodyMO/node-red-contrib-rcswitch2/files/2659629/Log_npmInstallFromTerminal.txt)
[Log_PaletteManagerInstall.txt](https://github.com/nobodyMO/node-red-contrib-rcswitch2/files/2659630/Log_PaletteManagerInstall.txt)

**Comment by nobodyMO** [comment]
The error does not occur during the installation of this Node-Red-Node but during the installation of the module rcswitch@0.3.1 .
This module is used as base and therefore implicitly installed. However, it has not been further developed for 3 years and is not compatible with nodejs 10.x.

Since it's not from me, I can't change anything. If this module is updated, the installation of the Node-Red-Node should work with nodejs 10.x as well.

**Comment by VogelP** [comment]
Thank you for the quick reply.
In the meantime i found this [Link](https://www.princetronics.com/how-to-read-433-mhz-codes-w-raspberry-pi-433-mhz-receiver/) that helped me to work around the problem.
After installing the 433Utils i then used an Exec Node to call CodeSend. It looks to me that it is also based on the original rcswitch files, although i could not find the version info 0.3.1. In any case i got it working this way, thanks again for your time and work.

**Comment by yeah887** [comment]
same issue

**Comment by nobodyMO** [comment]
Version 0.5.0 now suports nodejs up to 12
